### ISSUE TITLE
Compilation Failing

### ISSUE THREAD

**Issue by german23** [wasted/netflow#15]
Hi folks,

i tried setting up the netflow collector under Debian Jessie, however the compilation fails with:

[error] Unable to find credentials for [repo @ repo.wasted.io]

I cloned into the github repository and ran `./sbt compile`

We have valid proxy settings configured for the server and i can confirm that the request to "repo.wasted.io" get processed and forwarded by it. 

Anyone else got this error or is there anything i could do differently ?

Any feedback is appreciated

**Comment by fbettag** [comment]
Hi german23,

i know this error can be true if you try to access some of our private jars, but wasted-util 0.9.5 which is used here, does not have this. (as i can see in our webserver logs, it's giving 200s)

 $ curl -I http://repo.wasted.io//mvn/io/wasted/wasted-util_2.11/0.9.5/wasted-util_2.11-0.9.5.jar
HTTP/1.1 200 OK
Server: nginx
...

I must admint that sbt isn't the most solid tool i've encountered in my 8 year scala journey, but the quick fix for you to get it working is to put that jar (downloading it with curl/wget) and placing it in .ivy2/cache/io.wasted/wasted-util_2.11/jars/wasted-util_2.11-0.9.5.jar

Sorry for the fuzz, but we're phasing out this scala repo shortly and be replacing it with our golang version. (this version will still be on github, but likely with .old appended to the repo name).
So i'm not keen on fixing sbt issues (which is mainly the reason i am getting out of scala).
