### ISSUE TITLE
Unresolved dependencies while compiling

### ISSUE THREAD

**Issue by skoky** [wasted/netflow#16]
I am getting unresolved dependencies error while compiling / running the app:

> 
> [info] Resolving jline#jline;2.12.1 ...
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: io.wasted#wasted-util_2.11;0.9.+: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn] 	Note: Unresolved dependencies path:
> [warn] 		io.wasted:wasted-util_2.11:0.9.+ (/Users/lskokan/work/netflow/build.sbt#L19-33)
> [warn] 		  +- io.wasted:netflow_2.11:0.7.0
> sbt.ResolveException: unresolved dependency: io.wasted#wasted-util_2.11;0.9.+: not found

**Comment by fbettag** [comment]
I don't exactly recall what produced this, maybe broken resolvers or something. In any cast, quickest solution, clone https://github.com/wasted/scala-util (tag 0.9.x that you need) and run ./sbt publish-local

**Comment by skoky** [comment]
It's caused by inaccessible public repo http://repo.wasted.io/mvn

If I do publishLocal on scala-utils dependency works. 

And by the way, there is also issue with dependency `com.google.code.findbugs#jsr305;1.3.+` as it is very old version.
