### ISSUE TITLE
V9 records always lack duration

### ISSUE THREAD

**Issue by codingismy11to7** [wasted/netflow#18]
https://github.com/wasted/netflow/blob/1eb10a12b774753ef0149a411ee154cf53fe89a1/src/main/scala/io/netflow/flows/cflow/NetFlowV9.scala#L169
https://github.com/wasted/netflow/blob/1eb10a12b774753ef0149a411ee154cf53fe89a1/src/main/scala/io/netflow/flows/cflow/NetFlowV9.scala#L171

looks like these two lines need to be changed from `filter` to `filterNot`

**Comment by fbettag** [comment]
That looks about right. Would you mind opening a pull request?

**Comment by codingismy11to7** [comment]
#19
